//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeRates.Resources.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency charts.
        /// </summary>
        public static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China, Yuan Renminbi.
        /// </summary>
        public static string CNY_Desc {
            get {
                return ResourceManager.GetString("CNY_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNY.
        /// </summary>
        public static string CNY_Title {
            get {
                return ResourceManager.GetString("CNY_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bored programmers co.
        /// </summary>
        public static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro Member Countries, Euro.
        /// </summary>
        public static string EUR_Desc {
            get {
                return ResourceManager.GetString("EUR_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        public static string EUR_Title {
            get {
                return ResourceManager.GetString("EUR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom, Pound.
        /// </summary>
        public static string GBP_Desc {
            get {
                return ResourceManager.GetString("GBP_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        public static string GBP_Title {
            get {
                return ResourceManager.GetString("GBP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Everything.
        /// </summary>
        public static string Operation_Buy_Desc {
            get {
                return ResourceManager.GetString("Operation_Buy_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Operation_Buy_Title {
            get {
                return ResourceManager.GetString("Operation_Buy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference (Sell - Buy).
        /// </summary>
        public static string Operation_Diff_Desc {
            get {
                return ResourceManager.GetString("Operation_Diff_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        public static string Operation_Diff_Title {
            get {
                return ResourceManager.GetString("Operation_Diff_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Everything.
        /// </summary>
        public static string Operation_Sell_Desc {
            get {
                return ResourceManager.GetString("Operation_Sell_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Operation_Sell_Title {
            get {
                return ResourceManager.GetString("Operation_Sell_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Range_All {
            get {
                return ResourceManager.GetString("Range_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Range_Day {
            get {
                return ResourceManager.GetString("Range_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Range_Month {
            get {
                return ResourceManager.GetString("Range_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three days.
        /// </summary>
        public static string Range_ThreeDays {
            get {
                return ResourceManager.GetString("Range_ThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Range_Week {
            get {
                return ResourceManager.GetString("Range_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Range_Year {
            get {
                return ResourceManager.GetString("Range_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investing.Com.
        /// </summary>
        public static string SourceTitle_InvestingCom {
            get {
                return ResourceManager.GetString("SourceTitle_InvestingCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBU.
        /// </summary>
        public static string SourceTitle_NBU {
            get {
                return ResourceManager.GetString("SourceTitle_NBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obmenka Retail.
        /// </summary>
        public static string SourceTitle_ObmenkaRetail {
            get {
                return ResourceManager.GetString("SourceTitle_ObmenkaRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obmenka Wholesale.
        /// </summary>
        public static string SourceTitle_ObmenkaWholesale {
            get {
                return ResourceManager.GetString("SourceTitle_ObmenkaWholesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivatBank Cash.
        /// </summary>
        public static string SourceTitle_PrivatBankCash {
            get {
                return ResourceManager.GetString("SourceTitle_PrivatBankCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivatBank CashLess.
        /// </summary>
        public static string SourceTitle_PrivatBankCashLess {
            get {
                return ResourceManager.GetString("SourceTitle_PrivatBankCashLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Aggregator.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States, Dollar.
        /// </summary>
        public static string USD_Desc {
            get {
                return ResourceManager.GetString("USD_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD_Title {
            get {
                return ResourceManager.GetString("USD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide volatility.
        /// </summary>
        public static string VolatilityBtnTitle_Hide {
            get {
                return ResourceManager.GetString("VolatilityBtnTitle_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show volatility.
        /// </summary>
        public static string VolatilityBtnTitle_Show {
            get {
                return ResourceManager.GetString("VolatilityBtnTitle_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical volatility meters.
        /// </summary>
        public static string VolatilityMetersTitle {
            get {
                return ResourceManager.GetString("VolatilityMetersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volatility.
        /// </summary>
        public static string VolatilityTitle {
            get {
                return ResourceManager.GetString("VolatilityTitle", resourceCulture);
            }
        }
    }
}
