// <auto-generated />
using System;
using ExchangeRates.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExchangeRates.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    [Migration("20210411132656_AddVisitorDataStats")]
    partial class AddVisitorDataStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CurrencyAggregator.Models.CurrencyItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Buy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sell")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CurrencyAggregator.Models.FingerPrintData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VisitorDataItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("c")
                        .HasColumnType("int");

                    b.Property<DateTime?>("d")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("i")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("VisitorDataItemId");

                    b.ToTable("FingerPrintData");
                });

            modelBuilder.Entity("CurrencyAggregator.Models.PreparedDataItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreparedData");
                });

            modelBuilder.Entity("CurrencyAggregator.Models.VisitorDataItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VisitorStatistics");
                });

            modelBuilder.Entity("CurrencyAggregator.Models.FingerPrintData", b =>
                {
                    b.HasOne("CurrencyAggregator.Models.VisitorDataItem", null)
                        .WithMany("FingerPrints")
                        .HasForeignKey("VisitorDataItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
